# razavi/build-bundle.ps1
# Generate razavi-symbols.js from catalog.json + *.symbol.json + i18n-zh.json.
# Run from anywhere:  powershell -NoProfile -ExecutionPolicy Bypass -File razavi/build-bundle.ps1
# NOTE: keep this script ASCII-only; all non-ASCII text lives in i18n-zh.json.

$ErrorActionPreference = 'Stop'
$dir = Split-Path -Parent $MyInvocation.MyCommand.Path

$catalog = Get-Content (Join-Path $dir 'catalog.json') -Raw -Encoding UTF8 | ConvertFrom-Json
$i18n    = Get-Content (Join-Path $dir 'i18n-zh.json') -Raw -Encoding UTF8 | ConvertFrom-Json

# ---- categories in display order ----
$catArr = @()
foreach ($cid in $i18n.categoryOrder) {
    $catArr += [ordered]@{ id = $cid; name = $i18n.categories.$cid }
}

# ---- catalog entries (keep catalog order) ----
$entries = @()
foreach ($e in $catalog.entries) {
    $zh = $i18n.symbols.($e.symbolId)
    if (-not $zh) { $zh = $e.name }
    $entries += [ordered]@{
        id       = $e.symbolId
        name     = $e.name
        nameZh   = $zh
        category = $e.category
        palette  = ($e.palette -eq $true)
    }
}

# ---- symbol bodies ----
$symbols = [ordered]@{}
foreach ($e in $catalog.entries) {
    $p = Join-Path $dir $e.assetPath
    if (-not (Test-Path $p)) { throw "missing asset: $p" }
    $symbols[$e.symbolId] = Get-Content $p -Raw -Encoding UTF8 | ConvertFrom-Json
}

$nl = "`n"
$js = '/* GENERATED by razavi/build-bundle.ps1 -- do not edit by hand. Re-run the script after changing catalog/symbols/i18n. */' + $nl
$js += 'var RAZAVI_CATEGORIES = ' + ($catArr | ConvertTo-Json -Compress) + ';' + $nl
$js += 'var RAZAVI_CATALOG = ' + ($entries | ConvertTo-Json -Compress) + ';' + $nl
$js += 'var RAZAVI_SYMBOLS = ' + ($symbols | ConvertTo-Json -Compress -Depth 12) + ';' + $nl

$out = Join-Path $dir 'razavi-symbols.js'
[System.IO.File]::WriteAllText($out, $js, (New-Object System.Text.UTF8Encoding($false)))
Write-Host ("OK: {0} entries, {1} symbols -> {2} ({3:N1} KB)" -f $entries.Count, $symbols.Count, $out, ((Get-Item $out).Length / 1KB))
